### ISSUE TITLE
Feature Request: Full screen button should be added to top of apps in GNOME Shell-like taskbar.

### ISSUE THREAD

**Issue by temidaradev** [ZorinOS/zorin-taskbar#23]
It's bad that there is only a close button in the GNOME Shell-like taskbar for applications. I think a full screen button should be added as well.
![image](https://github.com/user-attachments/assets/5f9128ea-efe1-4562-8f66-6cbc347d3d98)

**Comment by ArtyomZorin** [comment]
Closing as this behaviour was set by the GNOME Shell-like layout in Zorin Appearance, not the Zorin Taskbar.

This was intentionally set in order to mirror the stock GNOME Shell layout, which doesn't have the maximize or minimize buttons by default.
However, we have recently released a software update to Zorin Appearance to display the maximize and minimize buttons in the GNOME Shell layout anyway to avoid confusion and improve the user experience.
